version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm-npmjs
    schedule:
      interval: 'daily'
    rebase-strategy: "disabled"
    reviewers:
      - '@peakon/tech-trooper'

