version: 2
aliases:
  - &docker_image
     - image: library/node:18.5.0

  - &restore_npm_cache
    keys:
      - npm-cache-{{ checksum "package.json" }}

  - &save_npm_cache
    key: npm-cache-{{ checksum "package.json" }}
    paths:
      - ./node_modules

  - &update_path
    name: Update PATH and Define Environment Variable at Runtime
    command: |
      echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      source $BASH_ENV
  - &npm_install
    name: NPM Install
    command: |
      npm install --no-audit -d
jobs:
  build:
    docker: *docker_image
    steps:
      - checkout
      - run: *update_path
      - restore_cache: *restore_npm_cache
      - run: *npm_install
      - save_cache: *save_npm_cache
      - run: *update_path
      - run: npm test
      - run: npm run lint

  publish:
    docker: *docker_image
    environment:
    steps:
      - checkout
      - run: *update_path
      - restore_cache: *restore_npm_cache
      - run: *npm_install
      - run:
          name: Publish to NPM
          command: |
            export NPM_TOKEN=${NPM_PUBLISH_TOKEN}
            npm publish --unsafe-perm --access public
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

experimental:
  notify:
    branches:
      only:
        - master
        - release

